name: Sandbox Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "sandbox"
        type: choice
        options:
          - "sandbox"

  push:
    branches:
      - "feature/**"
    paths:
      - "terraform/platform/**"
      - "terraform/modules/**"
      - ".github/workflows/sandbox.yml"
      - "terraform/environments/sandbox/**"

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-sandbox
  cancel-in-progress: false

jobs:
  terraform:
    name: Terraform Sandbox
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/platform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0

      - name: Verify Terraform version
        run: terraform version

      - name: Terraform Init
        working-directory: terraform/environments/sandbox
        run: terraform init -reconfigure

      - name: Terraform Validate
        working-directory: terraform/environments/sandbox
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/environments/sandbox
        run: terraform plan